PAIRS = ["BTCUSDT", "ETHUSDT", "SOLUSDT"]

COINGECKO_IDS = {
    "BTCUSDT": "bitcoin",
    "ETHUSDT": "ethereum",
    "SOLUSDT": "solana",
}

INTERVAL = "5"
BINANCE_INTERVAL = "5m"
MIN_CANDLES_FOR_SIGNALS = 26
MAX_CANDLES_STORED = 500

SMA_SHORT = 7
SMA_LONG = 25
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30

INITIAL_BALANCE = 10000.0
MAX_POSITION_PCT = 30
STOP_LOSS_PCT = 2.0
TAKE_PROFIT_PCT = 4.0
SIGNAL_CONFIDENCE_THRESHOLD = 60

WS_PING_INTERVAL = 20
WS_RECONNECT_DELAY = 5
COINGECKO_CACHE_TTL = 30

PRIMARY_SOURCE = "bybit"

SERVER_HOST = "0.0.0.0"
SERVER_PORT = 7860
